
const SEARCH_DOGS = 'SEARCH_DOGS';
const SORT_DOGS_ASC = 'SORT_DOGS_ASC';
const FETCH_DOGS_FAILED = 'FETCH_DOGS_FAILED';
const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
const FETCH_DOGS_REQUEST ='FETCH_DOGS_REQUEST';
const SORT_DOGS_DESC = 'SORT_DOGS_DESC';
const FETCH_DOGS_ID_SUCCESS =  'FETCH_DOGS_ID_SUCCESS';
const FETCH_DOGS_ID_REQUEST = 'FETCH_DOGS_ID_REQUEST';
const FETCH_DOGS_ID_FAILED = 'FETCH_DOGS_ID_FAILED';
const SORT_DOGS_WEIGHT_HIGHER = 'SORT_DOGS_WEIGHT_UP';
const SORT_DOGS_WEIGHT_LOWER = 'SORT_DOGS_WEIGHT_DOWN';

module.exports = {
    SEARCH_DOGS,
    SORT_DOGS_ASC,
    FETCH_DOGS_FAILED,
    FETCH_DOGS_SUCCESS,
    FETCH_DOGS_REQUEST,
    SORT_DOGS_DESC,
    FETCH_DOGS_ID_SUCCESS,
    FETCH_DOGS_ID_REQUEST,
    FETCH_DOGS_ID_FAILED,
    SORT_DOGS_WEIGHT_HIGHER,
    SORT_DOGS_WEIGHT_LOWER
}