
const SEARCH_DOGS = 'SEARCH_DOGS';
const SORT_DOGS_ASC = 'SORT_DOGS_ASC';
const FETCH_DOGS_FAILED = 'FETCH_DOGS_FAILED';
const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
const FETCH_DOGS_REQUEST ='FETCH_DOGS_REQUEST';
const SORT_DOGS_DESC = 'SORT_DOGS_DESC';
const FETCH_DOGS_ID_SUCCESS =  'FETCH_DOGS_ID_SUCCESS';
const FETCH_DOGS_ID_REQUEST = 'FETCH_DOGS_ID_REQUEST';
const FETCH_DOGS_ID_FAILED = 'FETCH_DOGS_ID_FAILED';
const SORT_DOGS_WEIGHT_HIGHER = 'SORT_DOGS_WEIGHT_UP';
const SORT_DOGS_WEIGHT_LOWER = 'SORT_DOGS_WEIGHT_DOWN';
const FETCH_TEMPERAMENTS_FAILED = "FETCH_TEMPERAMENTS_FAILED";
const FETCH_TEMPERAMENTS_SUCCESS = "FETCH_TEMPERAMENTS_SUCCESS";
const FETCH_TEMPERAMENTS_REQUEST = "FETCH_TEMPERAMENTS_REQUEST";
const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
const ADD_BREED_TO_DATABASE = 'ADD_BREED_TO_DATABASE';
const FILTER_BY_USER = 'FILTER_BY_USER';
const FILTER_BY_API = 'FILTER_BY_API';
const FILTER_BY_ALL = 'FILTER_BY_ALL';
const GO_TO_PAGE = 'GO_TO_PAGE';
const REMOVE_DOGS_ID = 'REMOVE_DOGS_ID';


module.exports = {
    GO_TO_PAGE,
    SEARCH_DOGS,
    SORT_DOGS_ASC,
    FETCH_DOGS_FAILED,
    FETCH_DOGS_SUCCESS,
    FETCH_DOGS_REQUEST,
    SORT_DOGS_DESC,
    FETCH_DOGS_ID_SUCCESS,
    FETCH_DOGS_ID_REQUEST,
    FETCH_DOGS_ID_FAILED,
    SORT_DOGS_WEIGHT_HIGHER,
    SORT_DOGS_WEIGHT_LOWER,
    FETCH_TEMPERAMENTS_FAILED,
    FETCH_TEMPERAMENTS_SUCCESS,
    FETCH_TEMPERAMENTS_REQUEST,
    FILTER_BY_TEMPERAMENT,
    ADD_BREED_TO_DATABASE,
    FILTER_BY_USER,
    FILTER_BY_API,
    FILTER_BY_ALL,
    REMOVE_DOGS_ID
}