const GET_ALL_DOGS = 'GET_DOGS';
const LOAD_RESULT = 'LOAD_RESULT';
const GET_DOG_DETAILS = 'GET_DOG_DETAILS'
const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS'

module.exports = {
    GET_ALL_DOGS,
    LOAD_RESULT,
    GET_DOG_DETAILS,
    GET_ALL_TEMPERAMENTS
}